### ISSUE TITLE
[Feat] FE 공용 컴포넌트 제작

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#11]
## Description
페이지 개발 이전에 공용컴포넌트를 각각 분리하여 제작합니다. 

## Estimated Duration
2월 4일 월요일 ~ 2월 5일 수요일 (2일)

## TO-DO
- [x] MobileLayout @sean2337 
- [x] Input 크기 별로 제작 @sean2337 
- [x] Margin @sean2337 
- [x] TyphoGraphy @sean2337 
- [x] FlexBox @sean2337 
- [x] DetailInfoBox 컴포넌트 제작 @sean2337 
- [x] Header @Pransinia 
- [x] NavigationBar @Pransinia 
- [x] Toast @Pransinia 
- [x] Button @Pransinia 
- [x] CarInfoBox @Pransinia

**Comment by Pransinia** [comment]
개발 완료!
